# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f97abf2b728d79b799dc3057295456fe04a9e073eaeb9c635d7b818f343fcb90d114441229c37ac7feda691d261afc3fa285822d1e3506d41ae7294ec4f3f2

test:
  secret_key_base: e952463658e730808a6aa1235cde27c94226a1f17f83e2f18df7a39e70b532c91914e01a65cc02633015e3ef817cbc6dcfa701c4998a21ab00968598cc3cbb23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
